services:
  pix-service:
    image: node:18
    container_name: pix-service
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    volumes:
      - ./pix-service.js:/app/index.js
      - ./pix-package.json:/app/package.json
      - ./certs:/app/certs:ro
    command: sh -c "apt-get update && apt-get install -y wget gnupg ca-certificates curl && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list && apt-get update && apt-get install -y google-chrome-stable && npm install --omit=dev && node index.js"
    networks:
      - pix-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  whatsapp-service:
    image: node:18
    container_name: whatsapp-service
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=3001
      - PIX_SERVICE_URL=http://pix-service:3000
      - WHATSAPP_ENABLED=true
      - DEBUG_MODE=false
      - SIMULATE_MODE=false
      - AUTO_FALLBACK=true
    volumes:
      - ./whatsapp-service.js:/app/index.js
      - ./whatsapp-package.json:/app/package.json
      - whatsapp-data:/app/data
    command: sh -c "apt-get update && apt-get install -y wget gnupg ca-certificates && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list && apt-get update && apt-get install -y google-chrome-stable && npm install --omit=dev && node index.js"
    networks:
      - pix-network
    depends_on:
      - pix-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pix-network
    depends_on:
      - pix-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  whatsapp-data:
    driver: local

networks:
  pix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16